name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node 18
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@blacha'
      
